// Static, curated nationality list for the admissions form. India is the
// default. Not a full ISO-3166 list, but broad enough for a real
// admissions application without shipping an exhaustive 195-country file.
export const NATIONALITY_OPTIONS = [
  "Indian",
  "Afghan",
  "Australian",
  "Bahraini",
  "Bangladeshi",
  "Bhutanese",
  "Brazilian",
  "Canadian",
  "Chinese",
  "Egyptian",
  "French",
  "German",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Japanese",
  "Jordanian",
  "Kenyan",
  "Kuwaiti",
  "Malaysian",
  "Maldivian",
  "Mauritian",
  "Mexican",
  "Burmese",
  "Nepali",
  "Dutch",
  "New Zealander",
  "Nigerian",
  "Omani",
  "Pakistani",
  "Filipino",
  "Qatari",
  "Russian",
  "Saudi",
  "Singaporean",
  "South African",
  "Korean",
  "Sri Lankan",
  "Swedish",
  "Swiss",
  "Thai",
  "Turkish",
  "Ugandan",
  "Ukrainian",
  "Emirati",
  "British",
  "American",
  "Vietnamese",
  "Other",
] as const;
